name: vertex-cover
channels:
  - defaults
dependencies:
  - ipykernel 
  - jupyter
  - jupyter_client
  - jupyter_console
  - jupyter_core
  - jupyter_server
  - jupyterlab
  - jupyterlab_pygments
  - jupyterlab_server
  - jupyterlab_widgets 
  - matplotlib 
  - numpy 
  - pandas
  - python
  - seaborn 
  - tqdm
  - networkx
